name: Fulcrum CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
      with:
        sdk-version: 19041

    - name: Create NuGet config para remover fonte não autorizada
      run: |
        if (Test-Path NuGet.Config) {
          Remove-Item NuGet.Config -Force
        }
        @"
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
          </packageSources>
        </configuration>
        "@ | Out-File NuGet.Config -Encoding utf8

    - name: Restore dependencies
      run: dotnet restore Fulcrum/Fulcrum.sln --configfile NuGet.Config

    - name: Build
      run: msbuild Fulcrum/Fulcrum.sln /p:Configuration=Release /p:Platform=x64 /p:AppxPackageSigningEnabled=false

    - name: Test
      run: dotnet test Fulcrum/Fulcrum.sln --no-restore --verbosity normal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Fulcrum-build
        path: |
          Fulcrum/bin/x64/Release/
          Fulcrum/AppPackages/